#-- Interfaz estática donde acceder a mi TFG y presentación.
markdown: kramdown
permalink: pretty
exclude: ['README.*', 'LICENSE.txt']
sass:
    style: expanded

# Título y subtítulo de la interfaz estática.
name: PLATAFORMA DE COMERCIO ONLINE MAD SERVICES
#subtitle:
subtitle: TFG de Alejandro Fernández Pérez

# Atributo del título de la página HTML.
title: MAD SERVICES

# Información para rastreadores web.
robots:
    description: One line of text describing the content of the page in less than 140 characters.
    keywords: foo, bar, baz
    crawl: index,follow

# La URL de la Página Web desplegada.
url: https://madservicesoficial.github.io/madservices-marketplace/

# La URL base.
baseurl: '/madservices-marketplace'

# Habilitación de Google Analytics y del consentimiento Cookie,
# de acuerdo al cumplimiento con la Ley de Cookies de la UE.
ga:
    account: 'UA-120960520-1'
    cookieconsent: true
    anonymizeip: true

# Configuración alternativa a Google Analytics que no necesita Cookies ni consentimiento de Cookie.
# Para más detalles: https://plausible.io/docs/outbound-link-click-tracking
plausible:
    domain: 'tsjensen.github.io'

# Imagen cuadrada del logo del TFG.
avatar: "./madservices.png"

# Enlaces a Redes Sociales.
links:
  - twitter:
      name: Twitter
      show: true
      href: https://twitter.com/madservicestick
      icon: fab fa-twitter
  - instagram:
      name: Instagram
      show: false
      href: https://instagram.com/madservicesoficial
      icon: fab fa-instagram
  - github:
      name: GitHub
      show: true
      href: https://github.com/madservicesoficial
      icon: fab fa-github
  - email:
      name: Email
      show: true
      href: mailto:madservices.co@gmail.com
      icon: fas fa-envelope
- linkedin:
      name: LinkedIn
      show: false
      href: https://linkedin.com/in/alejandro-fernández-pérez-65024119a/
      icon: fab fa-linkedin